#!/bin/bash
# /etc/NetworkManager/dispatcher.d/01ifupdown sets this values
INTERFACE=$IFACE

USER=andi

TIMESTAMP=`date`

EXPECTED_SSID="WIFI-PUBLIC"
SSID=`iwconfig $INTERFACE | grep $EXPECTED_SSID | cut -d":" -f2 | sed 's/^[^"]*"\|"[^"]*$//g'`

logger "WIFI-PUBLIC-autologin: check for wlan interface ($INTERFACE) and SSID ($SSID)."

if [ "$INTERFACE" == "wlan0" ]; then
  logger "WIFI-PUBLIC-autologin: detected $SSID"
  if [ "$SSID" == "$EXPECTED_SSID" ]; then
    . /home/${USER}/.nvm/nvm.sh
    nvm use v0.10.31
    if [ "$DEBUG" == "debug" ]; then
      logger "WIFI-PUBLIC-autologin: run WIFI auto login script on $SSID in DEBUG mode. open http://localhost:9000"
      phantomjs --remote-debugger-port=9000 src/app.js
    else
      logger "WIFI-PUBLIC-autologin: run WIFI auto login script on $SSID"
      phantomjs src/app.js
    fi
  else
    logger "WIFI-PUBLIC-autologin: nothing to do on $SSID"
  fi
fi
